(function(global){
'use strict';
function need(name){const api=global[name];if(!api)throw new Error('PravmirKnowledge: missing '+name);return api;}
function uniqSourceRecords(value){const out=[],seen=new Set(),walk=function(x){if(!x)return;if(Array.isArray(x)){x.forEach(walk);return;}if(typeof x!=='object')return;if(Array.isArray(x.source_records)){x.source_records.forEach(function(r){const key=[r.provider||'',r.source_id||'',r.source_file||'',r.source_url||''].join('|');if(!seen.has(key)){seen.add(key);out.push(Object.assign({},r));}});}Object.keys(x).forEach(function(k){if(k!=='source_records')walk(x[k]);});};walk(value);return out;}
async function init(){const apis=[need('PravmirData'),need('PravmirContent'),need('PravmirLiturgical'),need('PravmirEvents'),need('PravmirFood'),need('PravmirPilgrim'),need('PravmirNews'),need('PravmirLibrary')];await Promise.all(apis.map(function(api){return api.init?api.init():null;}));return getTrustSummary();}
async function getPlaceBundle(id){const ref={kind:'place',id:String(id||'')},data=need('PravmirData');const rows=await Promise.all([data.getPlaceById(ref.id),need('PravmirContent').getRelated(ref),need('PravmirEvents').getRelatedEvents(ref,{limit:100}),need('PravmirPilgrim').getForPlace(ref.id),need('PravmirNews').getRelatedNews(ref,{limit:100}),need('PravmirLibrary').getRelatedForTarget(ref.kind,ref.id,{limit:100})]);const bundle={ref:ref,place:rows[0],content:rows[1],events:rows[2],pilgrim:rows[3],news:rows[4],library_relations:rows[5]};bundle.provenance=uniqSourceRecords(bundle);return bundle;}
async function getFeastBundle(id){const ref={kind:'feast',id:String(id||'')};const rows=await Promise.all([need('PravmirLiturgical').resolveReference(ref),need('PravmirContent').getRelated(ref),need('PravmirEvents').getRelatedEvents(ref,{limit:100}),need('PravmirFood').getForFeast(ref.id),need('PravmirNews').getRelatedNews(ref,{limit:100}),need('PravmirLibrary').getRelatedForTarget(ref.kind,ref.id,{limit:100})]);const bundle={ref:ref,feast:rows[0],content:rows[1],events:rows[2],food:rows[3],news:rows[4],library_relations:rows[5]};bundle.provenance=uniqSourceRecords(bundle);return bundle;}
async function getRouteBundle(id){const ref={kind:'route',id:String(id||'')},data=need('PravmirData');const rows=await Promise.all([data.getRouteById(ref.id),need('PravmirContent').getRelated(ref),need('PravmirEvents').getRelatedEvents(ref,{limit:100}),need('PravmirPilgrim').getForRoute(ref.id),need('PravmirNews').getRelatedNews(ref,{limit:100}),need('PravmirLibrary').getRelatedForTarget(ref.kind,ref.id,{limit:100})]);const bundle={ref:ref,route:rows[0],content:rows[1],events:rows[2],pilgrim:rows[3],news:rows[4],library_relations:rows[5]};bundle.provenance=uniqSourceRecords(bundle);return bundle;}
async function getReadingBundle(id){const ref={kind:'reading',id:String(id||'')},lit=need('PravmirLiturgical'),lib=need('PravmirLibrary');const reading=await lit.resolveReference(ref),bridge=await lib.getScriptureForReading(ref.id),work=bridge?await lib.getWorkById(bridge.work_ref):null;const bundle={ref:ref,reading:reading,scripture_reference:bridge,work:work,work_url:work?lib.getDetailUrl(work):null};bundle.provenance=uniqSourceRecords(bundle);return bundle;}async function getSaintBundle(id){const ref={kind:'saint',id:String(id||'')},lit=need('PravmirLiturgical'),lib=need('PravmirLibrary');const rows=await Promise.all([lit.resolveReference(ref),lib.getLivesForSaint(ref.id,{limit:50}),lib.getRelatedForTarget(ref.kind,ref.id,{relation_type:'life_of',limit:50})]);const bundle={ref:ref,saint:rows[0],lives:rows[1],library_relations:rows[2]};bundle.provenance=uniqSourceRecords(bundle);return bundle;}
async function getDayBundle(date){const today=need('PravmirToday');const snapshot=await today.getSnapshot(date);return{snapshot:snapshot,provenance:uniqSourceRecords(snapshot)};}
async function getTrustSummary(){const news=need('PravmirNews'),pilgrim=need('PravmirPilgrim'),lib=need('PravmirLibrary');const rows=await Promise.all([news.getTrustSummary(),pilgrim.getTrustSummary(),lib.getTrustSummary()]);return{domains:9,news:rows[0],pilgrim:rows[1],library:rows[2],inferred_relations:Number(rows[0].inferred_relations||0)+Number(rows[2].inferred_relations||0),organisation_entities:Number(rows[0].organisation_entities||0)+Number(rows[2].organisation_entities||0),organisation_relations:Number(rows[1].organisation_relations||0)};}
global.PravmirKnowledge=Object.freeze({version:'1.39.0',init:init,getPlaceBundle:getPlaceBundle,getFeastBundle:getFeastBundle,getRouteBundle:getRouteBundle,getReadingBundle:getReadingBundle,getSaintBundle:getSaintBundle,getDayBundle:getDayBundle,getTrustSummary:getTrustSummary,collectProvenance:uniqSourceRecords});
})(window);
