(function(){
'use strict';
const TYPE_LABELS={scripture:'Священное Писание',theology:'Богословие',life:'Жития',prayer:'Молитвы',liturgy:'Богослужебные тексты',hymnography:'Гимнография',sermon:'Проповеди',catechesis:'Катехизация',church_history:'История Церкви'};
const RIGHTS_LABELS={public_domain_verified:'Общественное достояние',open_license:'Открытая лицензия',external_link_only:'Только внешняя ссылка',metadata_only:'Только metadata'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function typeLabel(v){return TYPE_LABELS[v]||v||'Произведение';}
function rightsLabel(v){return RIGHTS_LABELS[v]||v||'не указан';}
function externalAsset(x,label,detailUrl){const local=x.storage_mode==='local_text',license=x.license_url?' · <a href="'+esc(x.license_url)+'" target="_blank" rel="noopener noreferrer">лицензия</a>':'';return '<article class="library-policy"><strong>'+esc(label||x.title||x.asset_kind)+'</strong><span>'+esc(local?'Читать в ПМ':(x.media_kind||'Внешний текст'))+' · '+esc(rightsLabel(x.rights_status))+'</span><small><a href="'+esc(local?detailUrl:x.external_url)+'"'+(local?'':' target="_blank" rel="noopener noreferrer"')+'>'+(local?'Читать произведение':'Открыть внешний источник')+'</a>'+license+'</small></article>';}
function workCard(api,x){return '<article class="library-work-card"><div class="library-work-meta"><span>'+esc(typeLabel(x.work_type))+'</span><span>'+esc(rightsLabel(x.rights_status))+'</span></div><h3><a href="'+esc(api.getDetailUrl(x))+'">'+esc(x.title)+'</a></h3><p>'+esc(x.summary||'')+'</p><a class="library-work-open" href="'+esc(api.getDetailUrl(x))+'">Открыть произведение →</a></article>';}
function authorCard(x,active){return '<article class="library-policy'+(active?' is-active':'')+'"><strong><a href="'+esc(x.canonical_path)+'">'+esc(x.display_name)+'</a></strong><span>'+esc(x.summary)+'</span></article>';}
function setSelectOptions(select,rows,labels){rows.forEach(row=>{const opt=document.createElement('option');opt.value=row.value;opt.textContent=(labels[row.value]||row.value)+' ('+row.count+')';select.appendChild(opt);});}
function updateUrl(state,selectedAuthor){const p=new URLSearchParams();if(selectedAuthor)p.set('author',selectedAuthor.slug);if(state.q)p.set('q',state.q);if(state.work_type)p.set('type',state.work_type);if(state.rights_status)p.set('rights',state.rights_status);if(state.availability)p.set('availability',state.availability);history.replaceState(null,'',location.pathname+(p.toString()?'?'+p.toString():'')+location.hash);}
async function init(){
 const api=window.PravmirLibrary;if(!api)throw new Error('PravmirLibrary unavailable');
 const stats=await api.init(),boxes=document.querySelectorAll('#libraryStats>div strong');
 if(boxes[0])boxes[0].textContent=stats.works;if(boxes[1])boxes[1].textContent=stats.authors;if(boxes[2])boxes[2].textContent=stats.scripture_references;if(boxes[3])boxes[3].textContent=stats.text_assets+stats.media_assets;
 const params=new URLSearchParams(location.search),authorSlug=params.get('author'),selected=authorSlug?await api.getAuthorBySlug(authorSlug):null;
 const form=document.getElementById('libraryFilters'),query=document.getElementById('libraryQuery'),type=document.getElementById('libraryType'),rights=document.getElementById('libraryRightsFilter'),availability=document.getElementById('libraryAvailability'),reset=document.getElementById('libraryReset'),summary=document.getElementById('libraryResultSummary'),canonical=document.getElementById('libraryCanonical');
 const facets=await api.getDiscoveryFacets(selected?{author_ref:selected.id}:{});setSelectOptions(type,facets.work_types,TYPE_LABELS);setSelectOptions(rights,facets.rights_statuses,RIGHTS_LABELS);
 query.value=params.get('q')||'';type.value=params.get('type')||'';rights.value=params.get('rights')||'';availability.value=params.get('availability')||'';
 if(selected){const bundle=await api.getAuthorBundle(selected.id),view=document.getElementById('libraryAuthorView'),clear=document.getElementById('libraryClearAuthor');clear.hidden=false;view.hidden=false;view.innerHTML='<div><span class="section-label">Автор</span><h3>'+esc(selected.display_name)+'</h3><p>'+esc(selected.summary||'')+'</p></div><div class="library-author-stats"><strong>'+bundle.works.length+'</strong><span>произведений</span><strong>'+bundle.local_text_assets+'</strong><span>локальных текстов</span></div>';}
 async function render(){const state={q:query.value.trim(),work_type:type.value,rights_status:rights.value,availability:availability.value,author_ref:selected?selected.id:null,limit:500};const works=await api.getWorks(state);canonical.innerHTML=works.length?works.map(x=>workCard(api,x)).join(''):'<div class="library-state"><strong>Ничего не найдено.</strong><br>Измените запрос или фильтры. Новые canonical связи ради выдачи не создаются.</div>';summary.textContent='Найдено: '+works.length+' из '+facets.total+(selected?' · автор: '+selected.display_name:'');updateUrl(state,selected);}
 form.addEventListener('submit',e=>{e.preventDefault();render().catch(console.error);});
 query.addEventListener('input',()=>{if(query.value.trim().length===0||query.value.trim().length>=2)render().catch(console.error);});
 [type,rights,availability].forEach(el=>el.addEventListener('change',()=>render().catch(console.error)));
 reset.addEventListener('click',()=>{query.value='';type.value='';rights.value='';availability.value='';render().catch(console.error);});
 await render();
 const textCards=await Promise.all((await api.getTextAssets()).map(async asset=>{const work=await api.getWorkById(asset.work_ref);return externalAsset(asset,work?work.title:'Текст',api.getDetailUrl(work));}));
 const assets=[...textCards,...(await api.getMediaAssets()).map(x=>externalAsset(x,x.title))];document.getElementById('libraryAssets').innerHTML=assets.length?assets.join(''):'<div class="library-state">Пока нет текстовых материалов.</div>';
 const authors=await api.getAuthors({limit:100});document.getElementById('libraryAuthors').innerHTML=authors.map(x=>authorCard(x,!!selected&&x.id===selected.id)).join('');
 const policies=await api.getRightsPolicies();document.getElementById('libraryRights').innerHTML=policies.map(p=>'<article class="library-policy"><strong>'+esc(p.label)+'</strong><span>'+esc(p.description)+'</span><small>local text: '+(p.local_text_allowed?'allowed with evidence':'no')+' · local media: '+(p.local_media_allowed?'allowed with evidence':'no')+'</small></article>').join('');
 const trust=await api.getTrustSummary(),t=document.getElementById('libraryTrustSummary');if(t)t.innerHTML='<strong>Library trust:</strong> '+trust.canonical_works+' works · '+trust.scripture_references+' Scripture links · '+trust.text_assets+' text · '+trust.media_assets+' media · '+trust.relations+' explicit relations · inferred '+trust.inferred_relations+' · unlicensed local '+trust.unlicensed_local_assets;
}
document.addEventListener('DOMContentLoaded',()=>{init().catch(e=>{console.error(e);const n=document.getElementById('libraryCanonical');if(n)n.textContent='Не удалось загрузить библиотечный слой.';});});
})();
